### ISSUE TITLE
backupset.backup - description

### ISSUE THREAD

**Issue by marekmkmk** [CommvaultEngg/cvpysdk#10]
Description of backup function of backupset incorrectly states that backup function start full backup. Only first backup will be full. Next backups will be incremental.

> """Run full backup job for all subclients in this backupset.
>             Returns:
>                 list - list containing the job objects for the full backup jobs started for
>                         the subclients in the backupset

**Comment by GoelJatin** [comment]
Thanks for notifying.

The method description has been updated.
