### ISSUE TITLE
backupset.backup - waiting for job completion

### ISSUE THREAD

**Issue by marekmkmk** [CommvaultEngg/cvpysdk#11]
Backup function for backupset waits for a job completion. It should initiate a new and return result.

**Comment by GoelJatin** [comment]
It does not wait for job to complete.
It initiates backup job for all subclients in the backupset, and as soon as the backup job has been started for all, it returns a list consisting of the job objects.

**Comment by marekmkmk** [comment]
I tested it and it works as described. Script wait for a job completion.

**Comment by GoelJatin** [comment]
I'll verify this again, and get back to you. Although, as per the code, it doesn't wait for a job to complete.

Can you please try again, with more than one subclient in a backupset, and large backup size for the subclients.

**Comment by GoelJatin** [comment]
Just verified this again. It works as expected.

Initiates Backup job for sub-clients in the backup set, and returns a list of job objects, and does not wait for job completion.

I'm closing this issue. Please verify this again, and re-open if any queries.
