### ISSUE TITLE
API returns different response for `default` Subclient content

### ISSUE THREAD

**Issue by GoelJatin** [CommvaultEngg/cvpysdk#23]
Handle the response that is returned for a **default** subclient.

The API response is different for the **default** subclient of an Agent, and needs to be handled properly, as it raises _**KeyError**_

**Comment by rstep7** [comment]
I've also noticed a problem when trying to get the 'default' subclient for a postgresql backup.  The default exists, but it raises the KeyError mentioned above.

  File "/u01/app/python/lib/python3.6/site-packages/cvpysdk-1.0.0-py3.6.egg/cvpysdk/subclient.py", line 465, in get
    return self._subclients_dict[agent_name](
KeyError: 'postgresql'

**Comment by GoelJatin** [comment]
This is a different issue. Subclient class is the base class for all agents, and needs to be overwritten for the specific agent. Like it has been done for FS, VSA, SQL, and Cloud Apps, and needs to be added in the subclients dict.

![image](https://user-images.githubusercontent.com/14715892/32088892-5a6adf76-bb04-11e7-9300-fc688666a0e9.png)

SDK does not have support for postgresql currently, and will be added shortly.
After that you should not face this issue.

**Comment by rstep7** [comment]
Good to know.  Thanks for the update.  Is there a place where I can see the subclients that are being added?

**Comment by GoelJatin** [comment]
The README has been updated with the list of all Agents supported for subclient operations.

https://github.com/CommvaultEngg/cvpysdk#subclient-support

We'll keep on updating this list as and when any new agent is supported.

**Comment by GoelJatin** [comment]
Closing the issue as it no longer reproducible
