### ISSUE TITLE
run synthetic_full with BEFORE_SYNTH is not working

### ISSUE THREAD

**Issue by dheule** [CommvaultEngg/cvpysdk#26]
Hi, i try to start a synthetic_full job of a subclient.
`>>> job = subclient.backup('synthetic_full', True, 'BEFORE_SYNTH')`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "/usr/lib/python3.4/site-packages/cvpysdk/subclient.py", line 1489, in backup`
`    return self._process_backup_response(flag, response)`
`  File "/usr/lib/python3.4/site-packages/cvpysdk/subclient.py", line 800, in _process_backup_response`
`    raise SDKException('Response', '101', response_string)`
`cvpysdk.exception.SDKException: Response was not success`
`Incremental level for backup needs to be passed when runIncrementalBackup flag is set to true in backup request`

As you see, i set the Incremental level parameter, but the error says that the information is missing.

**Comment by GoelJatin** [comment]
Hi Daniel,

Some changes have been made to the API end-point. I'll update the SDK code as the per the modified API, and update the repository in this week.

Thanks for bringing this to our attention.

Thanks,
Jatin

**Comment by GoelJatin** [comment]
Daniel,

The code has been updated with the latest changes, including fix for this issue.
