### ISSUE TITLE
class to get all active jobs

### ISSUE THREAD

**Issue by dheule** [CommvaultEngg/cvpysdk#27]
**feature request**
We need a class to get all active jobs of a commcell, 
to start the backups of some clients if some other jobs are 
NOT running or to make some other cool tweaks of job control.

**Comment by spakhare** [comment]
We now have support to get list of active jobs using commcell object.

Ex: commcell_object.job_controller.active_jobs()

**Comment by dheule** [comment]
Cool job,

thank you !
