### ISSUE TITLE
agent class misses information if backup / restore is enabled

### ISSUE THREAD

**Issue by dheule** [CommvaultEngg/cvpysdk#28]
on the agent class, you can enable and disable backup / restores, 
but you can't get the current status to check if backup is enabled or not.

Please add .is_backup_enabled to the agent class.

**Comment by GoelJatin** [comment]
Hi,

Thanks for pointing this out. You are welcome to make the change, and open a PR, or let us know, and we can add this attribute.

-jatin

**Comment by dheule** [comment]
Hi Jatin,

sorry, i'm busy with developing a tool for our commvault enviroment with this cool sdk.
It doesn't hurt, but it would be great if you can add this. I can only report errrors at 
work time, and my freetime is realy limited atm.

Thank you,
Daniel

**Comment by GoelJatin** [comment]
Hi Daniel,

Sure, I understand.
I'll do it in the coming week.

Thanks,
Jatin

**Comment by GoelJatin** [comment]
Hi Daniel,

The attributes have been added. Please try with latest code from master.
