### ISSUE TITLE
Client instance does not support indexing?

### ISSUE THREAD

**Issue by ozskywalker** [CommvaultEngg/cvpysdk#36]
Experimenting with cvpysdk, but found it very curious that I can't iterate over the client list based on the examples provided so far.

Are you intending on changing this in time, or is there an alternative way you recommend achieving this?

```
>>> print(commcell.clients)
S. No.	       Client       

  1  	onedrive - dsc      
  2  	o365proxy1          
  3  	lockstep-baas4s     
  4  	iaas enhanced plan_indexserver
  5  	msp-o365-cs         
  6  	azure - dsc         
  7  	newyorkcity-disklib_systemcreatedsp_indexserver
  8  	new york city       
  9  	exchangeonline      
 10  	lockstep-baas6      
 11  	lockstep-baas2      
 12  	o365proxy2          
 13  	amazon - dsc        
 14  	lockstep-baas1      
 15  	msp-o365-exo        
 16  	o365-dsc            
 17  	lockstep-baas5s     
 18  	sqlserver_3
>>> commcell.clients
Clients class instance for Commcell: 'msp-o365-cs'
>>> commcell.clients[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'Clients' object does not support indexing
```

**Comment by ozskywalker** [comment]
Same as I extend into agents:

```
>>> client = commcell.clients.get('o365-dsc')
>>> client
Client class instance for Client: "o365-dsc"
>>> client.agents
Agents class instance for Client: 'o365-dsc'
>>> client.agents[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'Agents' object does not support indexing
>>> len(client.agents)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: object of type 'Agents' has no len()
```

**Comment by GoelJatin** [comment]
Hi Luke,

The clients attribute of the Commcell class instance is an object of the Clients class.

To get all the clients, you have to use the **all_clients** attribute from the clients object.
https://github.com/CommvaultEngg/cvpysdk/blob/master/cvpysdk/client.py#L499
**commcell.clients.all_clients**

Similarly for Agents:
https://github.com/CommvaultEngg/cvpysdk/blob/master/cvpysdk/agent.py#L163
**client.agents.all_agents**

Same is available across all classes.

**Comment by marekk1717** [comment]
Hi Jatin

IMHO all_* option should be available for all object types. For instance it doesn't work with organizations:
https://github.com/CommvaultEngg/cvpysdk/blob/dev/cvpysdk/organization.py

**Comment by ozskywalker** [comment]
> To get all the clients, you have to use the all_clients attribute from the clients object.
> https://github.com/CommvaultEngg/cvpysdk/blob/master/cvpysdk/client.py#L499
> commcell.clients.all_clients

Appreciate that, but it's not clear due to lack of documentation - if I have to read through the SDK code to figure it out, I'm not quite sure how it's expected for others to figure it out either.  

Can you get it documented?

It's unusual as well, generally when I'm consuming other SDKs too they're not trying to beautify the output for me either (ie. commcell.clients) and I am simply given an indexable object that I can iterate over - is there a design reason behind this?

**Comment by GoelJatin** [comment]
@marekk1717 Hi Marek,

The idea was to add it for all files, but somehow we must've missed it. I'll add this shortly, and go over the rest of the files as well to ensure it is present across all modules. Thanks for pointing this out.

**Comment by GoelJatin** [comment]
@ozskywalker Hi Luke,

This is already added to the doc-strings.
https://github.com/CommvaultEngg/cvpysdk/blob/master/cvpysdk/client.py#L65

The documentation did not got updated, not sure why. I'll check that and update it.

We also do not focus on beautifying the output, and it is only added so if someone tries to print the clients object, we return an output in human readable format which lists out all the clients.

I'll add iteration and indexing methods to the all objects for easier usage and implementations.

**Comment by ozskywalker** [comment]
Thanks Jatin
		
		

		//LW

	




On Tue, Mar 13, 2018 at 1:28 AM -0400, "Jatin Goel" <notifications@github.com> wrote:












@ozskywalker Hi Luke,


This is already added to the doc-strings.

https://github.com/CommvaultEngg/cvpysdk/blob/master/cvpysdk/client.py#L65


The documentation did not got updated, not sure why. I'll check that and update it.


We also do not focus on beautifying the output, and it is only added so if someone tries to print the clients object, we return an output in human readable format which lists out all the clients.


I'll add iteration and indexing methods to the all objects for easier usage and implementations.

**Comment by marekk1717** [comment]
Hi Jatin
Wouldn't it be just simplier to implement __iter__() and __next__() methods?

**Comment by GoelJatin** [comment]
Hi Marek,

We added those additional properties **all_*** to classes so we would return the internal dict, as there are / would be cases that require those details, so never thought that we should be adding these methods to the object itself.

Yes, we'll add them for ease of usage and understanding.

**Comment by GoelJatin** [comment]
FYI, SP11 code has been released, and the documentation has also been updated.

**SP11 Branch**: https://github.com/CommvaultEngg/cvpysdk/tree/SP11

**SP11 Release**: https://github.com/CommvaultEngg/cvpysdk/releases/tag/SP11

**PyPI**: https://pypi.python.org/pypi/cvpysdk

**Documentation**:  http://commvaultengg.github.io/cvpysdk

Please let us know if you see any issues.

This issue will be addressed as part of SP12, and updated on the **dev** branch after it's implemented.

**Comment by ozskywalker** [comment]
Thank you - looks like it's working in SP11 - closing issue

```
Python 3.5.0 (v3.5.0:374f501f4567, Sep 12 2015, 11:00:19) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from cvpysdk.commcell import Commcell
>>> commcell = Commcell('msp-showcase', 'admin', 'C0mmvault!')
>>> print(commcell.clients)
S. No.	       Client       

  1  	azurerm - dsc       
  2  	2_test plan renamed again_indexserver
  3  	cvvc01.cvirtual.lab 
  4  	amazon - dsc        
  5  	edgedrive           
  6  	newyorkcity_systemcreatedsp_indexserver
  7  	garbageclient       
  8  	msp-showcase        
  9  	laptop plan edge drive
 10  	msp-showcase.cvirtual.lab_analyticsserver
>>> commcell.clients.all_clients
{'azurerm - dsc': {'id': '11', 'hostname': 'azurerm - dsc'}, '2_test plan renamed again_indexserver': {'id': '13', 'hostname': '2_test plan renamed again_indexserver'}, 'cvvc01.cvirtual.lab': {'id': '3', 'hostname': 'cvvc01.cvirtual.lab'}, 'amazon - dsc': {'id': '12', 'hostname': 'amazon - dsc'}, 'edgedrive': {'id': '9', 'hostname': 'edgedrive'}, 'newyorkcity_systemcreatedsp_indexserver': {'id': '14', 'hostname': 'newyorkcity_systemcreatedsp_indexserver'}, 'garbageclient': {'id': '5', 'hostname': 'garbageclient.local'}, 'msp-showcase': {'id': '2', 'hostname': 'msp-showcase.cvirtual.lab'}, 'laptop plan edge drive': {'id': '10', 'hostname': 'laptop plan edge drive'}, 'msp-showcase.cvirtual.lab_analyticsserver': {'id': '4', 'hostname': 'msp-showcase.cvirtual.lab_analyticsserver'}}
>>> for i in commcell.clients.all_clients:
...     print(i)
... 
azurerm - dsc
2_test plan renamed again_indexserver
cvvc01.cvirtual.lab
amazon - dsc
edgedrive
newyorkcity_systemcreatedsp_indexserver
garbageclient
msp-showcase
laptop plan edge drive
msp-showcase.cvirtual.lab_analyticsserver
>>> commcell.clients.all_clients['azurerm - dsc']
{'id': '11', 'hostname': 'azurerm - dsc'}
>>> commcell.clients.all_clients['azurerm - dsc']['id']
'11'
>>> commcell.clients.all_clients['azurerm - dsc']['hostname']
'azurerm - dsc'
```

**Comment by GoelJatin** [comment]
Yes using all_clients will work.

We are also working on adding the support to directly iterate over the clients object for SP12.

I'll update you once the code is updated to the **dev** branch.

**Comment by GoelJatin** [comment]
Hi Luke,

Changes have been updated to the **dev** branch.

All SDK entities now support indexing, where you can give either the entity name / id, and it'll return your the details in case of name, and the name in case of id as input.

Please let me know if you see any other issues.

Thanks!
