### ISSUE TITLE
"Force All data (along with control) traffic into the tunnel"

### ISSUE THREAD

**Issue by marekk1717** [CommvaultEngg/cvpysdk#37]
/CommvaultEngg/cvpysdk/blob/dev/cvpysdk/network.py

There should be an option to set "Force All data (along with control) traffic into the tunnel" option for both DIRECT and GATEWAY connection types.

By default this option is set to False
"forceAllBackupRestoreDataTraffic": False,

**Comment by GoelJatin** [comment]
@marekk1717 Hi Marek,

We'll check this and get back to you.

**Comment by GoelJatin** [comment]
Hi @marekk1717 ,

Changes have been made and committed to the **dev** branch.

Please let us know if you see any other issues.

Closing this issue.

Thanks!
