### ISSUE TITLE
I am getting media agent exception: Response received is empty

### ISSUE THREAD

**Issue by Anu-26** [CommvaultEngg/cvpysdk#41]
>>> DiskLibraries(commcell)
DiskLibraries class instance for Commcell: 'windows2012r2'
>>> DiskLibrary(commcell, 'testlib')
DiskLibrary class instance for library: "testlib" of Commcell: "windows2012r2"

I am able to retrieve every value like storagepolicies,diskLibrary but for MediaAgent it is failing

>>> type(commcell.media_agents)
<class 'NoneType'>
>>>
>>>
>>> MediaAgents(commcell)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/cvpysdk-11.12-py3.6.egg/cvpysdk/storage.py", line 221, in __init__
    self.refresh()
  File "/usr/lib/python3.6/site-packages/cvpysdk-11.12-py3.6.egg/cvpysdk/storage.py", line 375, in refresh
    self._media_agents = self._get_media_agents()
  File "/usr/lib/python3.6/site-packages/cvpysdk-11.12-py3.6.egg/cvpysdk/storage.py", line 295, in _get_media_agents
    raise SDKException('Response', '102')
cvpysdk.exception.SDKException: Response received is empty
>>>
>>>
>>>

**Comment by spakhare** [comment]
Hi Anu,

commcell.media_agents should return "Response received is empty" only when there are no media agents installed on the commcell.

Can you please confirm if we have any media agent installed and get us the list of installed media agents on thecommcell?

You can find the installed Media Agents by navigating to Storage Resources | Media Agent from CommCell Browser.

For more details on Media Agents you can refer to below link: http://documentation.commvault.com/commvault/v11/article?p=8816.htm

If there are media agents installed, can you please get us the WebServer.log and WebConsole.log from 
"%COMMVAULT_INSTALL_DIRECTORY%/Log Files/" after running the same operation (commcell.media_agents).

**Comment by Anu-26** [comment]
Hi,

I have used the same system as media agent where commserv is installed and under storage resources -> MediaAgent->windows2012r2 is showing as media agent.

Attached are the logs
[WebConsole.log](https://github.com/CommvaultEngg/cvpysdk/files/2084100/WebConsole.log)
[WebServer.log](https://github.com/CommvaultEngg/cvpysdk/files/2084103/WebServer.log)

**Comment by spakhare** [comment]
Can you please share the Service pack level of the commcell?

**Comment by Anu-26** [comment]
It is SP10

**Comment by GoelJatin** [comment]
Hi Anu,

It would be a little helpful for us if you could run the following commands and share the output:

response = commcell.request('GET', 'MediaAgent')
print(response)
print(response.status_code)
print(response.text)
print(response.json())

And also, share the snapshot from the console, where the media agents are listed correctly.

This would be helpful for us to start with.

We'll analyse these and get back to you if we need any more info.

Thanks.

**Comment by spakhare** [comment]
Hi Anu,

The issue here is because you are using the SP12 version of cvpysdk. 

Can you please give a try with SP10 branch? You can get the SP10 version from below location.
https://github.com/CommvaultEngg/cvpysdk/tree/SP10

Let us know if you face any issues.

Thanks.

**Comment by Anu-26** [comment]
Hi All,

I am getting the media agent after trying with SP10 version of cvpysdk.
 
>>
>>> response = commcell.request('GET', 'MediaAgent')
>>> print(response)
<Response [200]>
>>> print(response.status_code)
200
>>> print(response.text)
}name":"windows2012r2","id":2
>>> print(response.json())
{'response': [{'entityInfo': {'name': 'windows2012r2', 'id': 2}}]}
>>>

Thanks for the quick help 👍

**Comment by GoelJatin** [comment]
Sure Anu! Anytime.

Do let us know if you see any other issues.

Closing the issue!
