### ISSUE TITLE
 encoded = binascii.b2a_base64(s, newline=False)

### ISSUE THREAD

**Issue by Anu-26** [CommvaultEngg/cvpysdk#42]
Hi

I am using version SP10 cvpysdk and getting below error while adding disk library.

[root@CentOS68_base ~]# python3
Python 3.6.5 (default, Apr 10 2018, 16:33:12)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-18)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cvpysdk.commcell import Commcell;
>>> commcell = Commcell('10.207.84.161', 'Administrator', 'Password123!');
>>> from cvpysdk import storage;
>>> from cvpysdk.storage import *;
>>> commcell.disk_libraries.add(library_name="testlib2", media_agent="windows2012r2", mount_path="C:\test2", username="Administrator", password="Password123!")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/cvpysdk-1.0.0-py3.6.egg/cvpysdk/storage.py", line 550, in add
    "password": b64encode(password),
  File "/usr/lib/python3.6/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'
>>>

**Comment by GoelJatin** [comment]
Hi Anu,

This is something we must've missed while adding support for Python 3.

Thanks for pointing this out.

We'll fix this soon and update you.

**Comment by GoelJatin** [comment]
Hi Anu,

I've made the fix and pushed to the SP10 tree.
