### ISSUE TITLE
Query to edit subclient properties using commvault python SDK

### ISSUE THREAD

**Issue by Anu-26** [CommvaultEngg/cvpysdk#43]
Hi,

It is not an issue but a query as I didn't find any other mode for my query to get resolved. So raised issue for the same.

My query is through commvault python SDK is it possible to edit  properties of storage policy or subcient?
Example: I don't want to use deduplication,encrytion and compression which by default is enabled while creating the subclient.
So is there any way from sdk to disable those or edit the properties of subclient,storage policies,disk lib etc.

**Comment by GoelJatin** [comment]
Hi Anu,

You can reach out to us anytime using GitHub Issues or at our mailing address Dev-PythonSDK@commvault.com

Coming to your query, we generally write getters and setters for updating the properties of a subclient.

Example:

Get Storage Policy of a subclient:

[subclient.storage_policy](https://github.com/CommvaultEngg/cvpysdk/blob/SP12/cvpysdk/subclient.py#L1183-L1190)


Set Storage Policy of a subclient:

[subclient.storage_policy = "new_policy"](https://github.com/CommvaultEngg/cvpysdk/blob/SP12/cvpysdk/subclient.py#L1325-L1359)


Please share a list of properties that you wish to update, and we'll see how best they can be added.

You can call the internal method [_set_subclient_properties](https://github.com/CommvaultEngg/cvpysdk/blob/SP12/cvpysdk/subclient.py#L864), if its an immediate requirement.

**Comment by Anu-26** [comment]
Hi Jatin,

I want to disable deduplication,software compression and encryption which are the properties of subclient.

Below is traverse path:
1.Disable the deduplication option which is under storage device the properties of already created subclient.
2.Disable Software compression under data transfer option of subclient.
3.Mark encryption to none which is under advance option of subclient.

I also checked the _set_subclient_properties method having two arguments attr_name, value.
Now that I want to disable deduplication what values should I set to attr_name and value.

**Comment by GoelJatin** [comment]
Hi Anu,

I'll get back to you with the details shortly.

**Comment by Anu-26** [comment]
Hi Jatin,
Any update.

**Comment by Anu-26** [comment]
Thanks Jatin for adding getters and setters for the properties that I mentioned.

**Comment by GoelJatin** [comment]
Hi Anu,

The code has been pushed to the **dev** branch.

Please let us know if you see any issues.

**Comment by Anu-26** [comment]
Hi Jatin,

I am able to change value for generateSignature but for disabling deduplication it is throwing an error.

>> subclient.deduplication_options
'ON_MEDIA_AGENT'
>>>


>>> subclient._set_subclient_properties("_commonProperties['storageDevice']['deDuplicationOptions']['generateSignature']", 'ON_CLIENT')
>>> subclient = backupset.subclients.get('nfssc1')
>>> subclient.deduplication_options
'ON_CLIENT'


>> subclient._set_subclient_properties("_commonProperties['storageDevice']['deDuplicationOptions']['enableDeduplication']", 'FALSE')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/cvpysdk-1.0.0-py3.6.egg/cvpysdk/subclient.py", line 655, in _set_subclient_properties
    output = self._process_update_response(flag, response)
  File "/usr/lib/python3.6/site-packages/cvpysdk-1.0.0-py3.6.egg/cvpysdk/subclient.py", line 740, in _process_update_response
    raise SDKException('Response', '101', response_string)
cvpysdk.exception.SDKException: Response was not success
}errorMessage":"Service error","errorCode":102
>>>
>>>

**Comment by GoelJatin** [comment]
Hi Anu,

Can you please try from the public getters and setters?

# disable deduplication
subclient.deduplication_options = (False, None)

# enable deduplication
subclient.deduplication_options = (True, {"ON_CLIENT" / "ON_MEDIA_AGENT"})

[https://github.com/CommvaultEngg/cvpysdk/blob/dev/cvpysdk/subclient.py#L2041](dedpulication_options)

**Comment by Anu-26** [comment]
Hi Jatin,

Below is the output

>>> subclient.software_compression
'OFF'
>>>
>>> subclient.software_compression = ('USE_STORAGE_POLICY_SETTINGS')
>>> subclient = backupset.subclients.get('nfssc1')
>>> subclient.software_compression
'USE_STORAGE_POLICY_SETTINGS'
>>> subclient = backupset.subclients.get('nfssc1')
>>> subclient.deduplication_options
'ON_CLIENT'
>>>
>>> subclient.deduplication_options = (False, None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/cvpysdk-1.0.0-py3.6.egg/cvpysdk/subclient.py", line 1623, in deduplication_options
    "enableDeduplication": enable_dedupe,
  File "/usr/lib/python3.6/site-packages/cvpysdk-1.0.0-py3.6.egg/cvpysdk/subclient.py", line 655, in _set_subclient_properties
    output = self._process_update_response(flag, response)
  File "/usr/lib/python3.6/site-packages/cvpysdk-1.0.0-py3.6.egg/cvpysdk/subclient.py", line 740, in _process_update_response
    raise SDKException('Response', '101', response_string)
cvpysdk.exception.SDKException: Response was not success
}errorMessage":"Service error","errorCode":102
>>>
>>>
>>> subclient = backupset.subclients.get('nfssc1')
>>> subclient.deduplication_options
'ON_CLIENT'
>>>
>>>
>>>

**Comment by Anu-26** [comment]
Hi Jatin,

It is working after uninstalling  and installing it again. 

>>> subclient.deduplication_options
'ON_CLIENT'
>>> subclient.deduplication_options = (False, None)
>>> subclient = backupset.subclients.get('nfssc1')
>>> subclient.deduplication_options
False
>>>


Thanks for the help

**Comment by GoelJatin** [comment]
Hi Anu,

There was a small issue that I missed in the older fix.

I've made the fix and pushed the updated subclient.py file to the **dev** branch.

Please download that file, and you can replace it directly under:

%PYTHON_FOLDER%\Lib\site-packages\cvpysdk-11.13-py3.6.egg\cvpysdk\

Please let us know if you see any more issues.

Closing the issue.
