### ISSUE TITLE
Multistream and disklibrary/media_agent deletion code.

### ISSUE THREAD

**Issue by Anu-26** [CommvaultEngg/cvpysdk#44]
Hi All,

Following are the few things which I can’t find in scripts and if it is there I might be missing it.
It would be really great if you  point me to correct location or add all these  in SP10 to latest version of commvault.

We require all these parameters in our  environment which we are planning to execute using available commvault python sdk

Deletion Process:
1.Deletion of DiskLibrary
2.Deletion of Media agent.
3.Deletion of jobs from: Storage policy --> right click on "Primary" --> view--> jobs --> delete the job

Enabling multistream option in subclient:
1.Subclient --> right click and select properties --> advance --> Entering value 2 to 'performance number of data readers' and
enable checkbox of Allow multiple data readers within a drive or mount point.

**Comment by GoelJatin** [comment]
Hi Anu,

1. Deletion of Disk Library:
You can delete a disk library from the below call

>>> commcell.disk_libraries.delete(library_name)

[https://github.com/CommvaultEngg/cvpysdk/blob/dev/cvpysdk/storage.py#L83](Delete a Disk Library)

2. Deletion of Media agent:
We did not add support for a Media Agent deletion, as a media agent deletion involves some other operations, like there should be no library mounted on that media agent, etc., and currently have no plans for adding that support.
Please let us know if it is an immediate requirement, and we can discuss and let you know.

Rest all, we'll check and get back to you early next week.

**Comment by Anu-26** [comment]
Hi Jatin,
Thanks for the update.

**Comment by GoelJatin** [comment]
Hi Anu,

Regarding your other requirements, we are discussing it internally, and will update you accordingly.

**Comment by shailymehta** [comment]
Hi Anu,

1. For subclient properties, we have below getter and setter:
    a. number of data readers:
        subclient_obj.data_readers
        [https://github.com/CommvaultEngg/cvpysdk/blob/dev/cvpysdk/subclient.py#L1225]
     
        subclient_obj.data_readers = <int value>
        [https://github.com/CommvaultEngg/cvpysdk/blob/dev/cvpysdk/subclient.py#L1233]

    b. Allow multiple data readers within a drive or mount point:
        subclient_obj.allow_multiple_readers
        [https://github.com/CommvaultEngg/cvpysdk/blob/dev/cvpysdk/subclient.py#L1251]

        subclient_obj.allow_multiple_readers = True/False
        [https://github.com/CommvaultEngg/cvpysdk/blob/dev/cvpysdk/subclient.py#L1259]

2. For deleting job from any copy:
    storage_policy_obj.delete_job(job_id, storage_policy_name, copy_name )
    [https://github.com/CommvaultEngg/cvpysdk/blob/dev/cvpysdk/policies/storage_policies.py#L1043]

**Comment by Anu-26** [comment]
Hi Shaily,

All the parameters are running perfectly.
Thanks :)

**Comment by GoelJatin** [comment]
Closing the issue!

Please let us know if you have any other doubts / requirements.
