### ISSUE TITLE
Turn off Software Compression from Storage Policy

### ISSUE THREAD

**Issue by cssupratik** [CommvaultEngg/cvpysdk#46]
Hello  Team,

I was trying to create a Storage Policy (without Software Compression and without Encrypt Data) for a Disk Library. 
I have noticed that by default Encrypt Data is Turned Off and Software Compression is Turned On.
So, I want to know how to Turn Off Software Compression from the Storage Policy?

Below is the Setup and Steps Details : 
My CV Test MAchine Setup is CV11SP10
My CV Python SDK is version : CV11SP11 

Steps Executed :
>>>commcell.disk_libraries.add(library_name="nfsdev2sp10", media_agent="rhel74-cv11sp10", mount_path="/mnt/ddr_cv11sp10auto")
DiskLibrary class instance for library: "nfsdev2sp10" of Commcell: "sup-cv11sp10"

>>> commcell.disk_libraries.add(library_name="nfsdev2sp10", media_agent="rhel74-cv11sp10", mount_path="/mnt/ddr_cv11sp10auto")
DiskLibrary class instance for library: "nfsdev2sp10" of Commcell: "sup-cv11sp10"

When i checked in Commcell Console : above created policy has Software Compression Turned On (On clients)

**Comment by GoelJatin** [comment]
Hi @cssupratik ,

We'll check this shortly and get back to you.

**Comment by cssupratik** [comment]
Hi Jatin,
Any update on this Storage Policy issue?

**Comment by GoelJatin** [comment]
Hi @cssupratik 

Apologies for the delay.

We are working on adding an argument to the Storage Policy add method, to disable Software Compression.

We'll update you once we've committed the code on the [SP11](https://github.com/CommvaultEngg/cvpysdk/tree/SP11) tree.

**Comment by GoelJatin** [comment]
@shailymehta,

Can you please share an update on this.

**Comment by klogan12** [comment]
Please open Commvault support ticket.
