### ISSUE TITLE
Showing different size of disk library while creating it using sdk and manually using cifs share through network path.

### ISSUE THREAD

**Issue by Anu-26** [CommvaultEngg/cvpysdk#47]
Hi,
I am creating the disk library using network path for CIFS share.
I observed 2 different output while creating the disk library manually and the other with SDK.
Using Commvault SDK version- SP11

With SDK-
It is giving me space of windows machine instead of the backup media/disk library.
commcell.disk_libraries.add(library_name="tl1", media_agent="windows2012r2_mediaagent", mount_path="\\at86.chs.local\ct", username="admin", password="123")
DiskLibrary class instance for library: "tl1" of Commcell: "windows2012r2"
![sdk](https://user-images.githubusercontent.com/30489007/43639762-eebde250-973a-11e8-870c-33cbdf818a69.png)

Manually-
But when I create the disk library manually passing same values to the field using network path it is showing the actual disk size of backup media which is correct output.
![manual](https://user-images.githubusercontent.com/30489007/43639772-fe82c598-973a-11e8-9e22-10a2e2cd7ce5.png)

Am I missing something here.

**Comment by GoelJatin** [comment]
Hi @Anu-26 ,

This seems like some API / back-end issue.

Can you please open a TR. Respective teams will take a look and update you.

Thanks,
Jatin

**Comment by Anu-26** [comment]
Hi Jatin,

I don't know what is TR.Can you please tell me from where to open a TR.

Regards,
Anmol

**Comment by GoelJatin** [comment]
Please contact Commvault customer support, and they'll open a ticket, and help you resolving this issue.
