### ISSUE TITLE
batch API request

### ISSUE THREAD

**Issue by sathaley1** [CommvaultEngg/cvpysdk#5]
Hi,
If we add functionality to create batch request for commvault REST APIs, it will be beneficial for invoking multiple API requests in one batch. Currently we have to call each API one by one. If we have a function to create a batch of a specific number of API requests say 10 or 25 then the user can create a batch of all the requests and then execute at once. A unique string identifier can be provided by the user for each API request and the same identifier will be returned with the response so that user will be able to identify which response is associated with which API request. We can add a method like "batch_request" in commcell.py.

**Comment by GoelJatin** [comment]
Nice idea.
You can make the enhancement and open a Pull Request on the **dev** branch.

**Comment by GoelJatin** [comment]
Is there any progress on this?

**Comment by GoelJatin** [comment]
Closing this issue, as there has been no progress on this in long time.
