### ISSUE TITLE
finding the global filter status of subclient

### ISSUE THREAD

**Issue by shruthijanakiram** [CommvaultEngg/cvpysdk#50]
Can I know the python SDK command to find the global filter status and to enable it?

**Comment by GoelJatin** [comment]
Hi @shruthijanakiram ,

You can select the Global filters from the Commcell object:
`>>> commcell.global_filters`

You can find more details for the global filters supported operations here:
[Global Filters](https://commvaultengg.github.io/cvpysdk/globalfilter.html)

**Comment by shruthijanakiram** [comment]
>>> commcell.global_filters

The above command will provide comcell level global filter status. But how can we get the subclient level global filter status.

**Comment by GoelJatin** [comment]
@spakhare ,

Sachin, can you please help Shruthi here.

**Comment by spakhare** [comment]
Hi @shruthijanakiram 

As of now we don't have support for this. Will update here, once we add the support for this.

**Comment by shruthijanakiram** [comment]
But i see global filter module. What operation does that module perform

**Comment by spakhare** [comment]
That module is to add filters at global level (commcell level).

**Comment by GoelJatin** [comment]
Hi @shruthijanakiram ,

We've added support for global filters at Subclient level for File System.

[GET Global filter status value](https://github.com/CommvaultEngg/cvpysdk/blob/dev/cvpysdk/subclients/fssubclient.py#L992)

[SET Global filter status value](https://github.com/CommvaultEngg/cvpysdk/blob/dev/cvpysdk/subclients/fssubclient.py#L999)

The code is updated on the [**dev**](https://github.com/CommvaultEngg/cvpysdk/tree/dev/) branch.

Please give it a try, and let us know if you see any issues.

**Comment by GoelJatin** [comment]
Closing the issue, assuming this worked as expected.
