### ISSUE TITLE
Modifying Storage Policy Properties for Multi Streaming

### ISSUE THREAD

**Issue by cssupratik** [CommvaultEngg/cvpysdk#51]
Hi,

I wanted to modify few Storage Policy Properties in order to configure Multi Streaming Backup Jobs.

By default when create Storage Policy using CVPySDK SP11 with below code : 

from cvpysdk.commcell import Commcell
commcell = Commcell('10.110.1.210', 'administrator', 'Password123')
commcell.storage_policies.add(storage_policy_name='auto_nfs_stg_pol_1',
                                                            library='auto_nfs_disk_lib_1',
                                                            media_agent='rhel74xxx')

And then check the same Storage Polices Properties in CV GUI,
I can see the default values of below properties:
 "Device Stream = 1"
"enable stream randomization = False/Unchecked"
"distribute data evenly among multiple streams = False/Unchecked"

And i wanted to modify these default values like below : 
 "Device Stream = 50"
"enable stream randomization = True"
"distribute data evenly among multiple streams = True"

Could you please tell me any method to modify these storage policy properties?
or is it possible to pass these values while creating new storage policy?
![cv_upload_sp1](https://user-images.githubusercontent.com/41724016/44831763-9d810780-ac45-11e8-9460-66bcf6ae6164.jpg)

**Comment by shailymehta** [comment]
@cssupratik

We are working on SP property update support, Will update you once we have this checked in.

**Comment by cssupratik** [comment]
@shailymehta 

Any update on the check in?

Regards,
Supratik

**Comment by klogan12** [comment]
Please open Commvault support ticket.
