### ISSUE TITLE
Status for support for expert storage configuration

### ISSUE THREAD

**Issue by Anu-26** [CommvaultEngg/cvpysdk#52]
Hi,
Is there a support for expert storage configuration under the storage tab?
If support is there can you please point me to the script and if not is it in a plan to automate it.
Below are screenshots I have attached step by step for expert storage configuration.

![repl1](https://user-images.githubusercontent.com/30489007/44978944-7a2dc380-af89-11e8-9b9a-8daee0d06fee.png)
![repl2](https://user-images.githubusercontent.com/30489007/44978982-8f0a5700-af89-11e8-8438-00b18f48d27e.png)
![repl3](https://user-images.githubusercontent.com/30489007/44979046-bc570500-af89-11e8-917b-21403c17fb27.png)

Regards,
Anmol

**Comment by GoelJatin** [comment]
@shailymehta,

Can you please check this.

**Comment by shailymehta** [comment]
@GoelJatin @Anu-26 
Will check and get back.

**Comment by shailymehta** [comment]
Hi @Anu-26 
The share mount path folder functionality is added in storage.py:
https://github.com/CommvaultEngg/cvpysdk/blob/master/cvpysdk/storage.py#L882

**Comment by Anu-26** [comment]
Hi Shaily,

Sorry for late response .
Is it possible to add code changes  support to CV11 SP11 branch because we are using code of  CV11 SP11 branch and also all our commvault setups are on SP11 .

**Comment by klogan12** [comment]
Please open Commvault support ticket.
