### ISSUE TITLE
Changing the Default Chunk Size from Storage Policy Settings

### ISSUE THREAD

**Issue by cssupratik** [CommvaultEngg/cvpysdk#53]
Hi CommvaultEngg Team,

I need some information regarding changing the Default Chunk Size from Commvault-Python SDK.
Is there any way we can modify the default Chunk Size from 4096 Mb to any larger size like 8192 or 12288 MB from CV-Python SDK?

It is required for Backup Performance optimization (increasing Throughput).
Manually we can do this change by below option : 
Storage Policy --> Primary Copy --> Properties --> Data Paths --> Properties

I am using  Commvault Python SDK version :  CV11SP11

![cv_upload_chunk_size](https://user-images.githubusercontent.com/41724016/46934217-8ae75400-d074-11e8-8de8-eda5fcff6027.jpg)

**Comment by klogan12** [comment]
Please open Commvault support ticket.
