### ISSUE TITLE
Opnestack VirtualServer instance object NONE type

### ISSUE THREAD

**Issue by narabeltala** [CommvaultEngg/cvpysdk#55]
from cvpysdk.commcell import Commcell
commcell = Commcell("host", "admin", "password")
client = commcell.clients.get("dc_vim1")
agent = client.agents.get('virtual server')
instance=agent.instances.get('openstack') ==> gives NoneType

>>> print agent.instances
S. No.        Instance                 Agent                   Client
  1     openstack               virtual server          dc2_vim1

>>> backupset=agent.backupsets.get('wf_test1_dc2')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Python27\lib\site-packages\cvpysdk-11.14-py2.7.egg\cvpysdk\backupset.py", line 484, in get
    self._backupsets[backupset_name]["id"]
  File "c:\Python27\lib\site-packages\cvpysdk-11.14-py2.7.egg\cvpysdk\backupset.py", line 586, in __init__
    self._agent_object = self._instance_object._agent_object
AttributeError: 'NoneType' object has no attribute '_agent_object'

>>> print agent.backupsets
S. No.       Backupset                Instance                 Agent                   Client

  1     wf_test2_swag111        openstack               virtual server          dc2_vim1
  2     wf_test2_swag           openstack               virtual server          dc2_vim1
  3     wf_test1_dc2            openstack               virtual server          dc2_vim1
  4     custom                  openstack               virtual server          dc2_vim1
  5     wf_multitenancy_vdc     openstack               virtual server          dc2_vim1
  6     wf_new_test_dc2x        openstack               virtual server          dc2_vim1
  7     wf_upa_dc2              openstack               virtual server          dc2_vim1
  8     defaultbackupset        openstack               virtual server          dc2_vim1
>>>

**Comment by klogan12** [comment]
We dont have open stack support part of our SDK.  This is on our road map.

**Comment by narabeltala** [comment]
Thanks a lot for the response. Same thing I just found inside class
VirtualServerInstance(Instance). For us this is kind of urgent. Can you
please give us some pointers with which we can write this missing code to
handle Virtual server for openstack.

Thanks again.
Regards
Soumya

**Comment by narabeltala** [comment]
And also what are other ways to automate handling of Openstack based
Virtual server in Commvault

**Comment by GoelJatin** [comment]
Hi @narabeltala ,

The support for OpenStack has been added to the [dev](https://github.com/CommvaultEngg/cvpysdk/tree/dev) branch.

Please install the SDK from the **dev** branch, and try it out.

Let us know if you have / face any other issues / concerns.

**Comment by narabeltala** [comment]
Thanks Jatin for the same. We have downloaded and trying an out of place
restore. WIll update.
