### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by AndreeaItu** [CommvaultEngg/cvpysdk#56]
Hi,

I'm trying to fetch the clients from the commcell using the sample commands offered by Commvault for the python module but I get the following error:

>>> from cvpysdk.commcell import Commcell
>>> client = commcell.clients.get('cloudma')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'get'

>>> print(cvpysdk.__version__)
1.0.0

Currently I am running on SP9, Python version 3.7.1

Thank you,

Andreea Itu

**Comment by klogan12** [comment]
You need to create commcell object.

commcell = Commcell(webconsole_hostname, commcell_username, commcell_password)

**Comment by AndreeaItu** [comment]
It is already created.
I've tried again, but the issue persists.

>>> from cvpysdk.commcell import Commcell
>>> commcell = Commcell("172.30.61.162","test")
Please enter the Commcell Password:
>>> client = commcell.clients.get('cloudma')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'get'
