### ISSUE TITLE
organization.py email validation

### ISSUE THREAD

**Issue by marekk1717** [CommvaultEngg/cvpysdk#57]
organization.py line 342 should be fixed. Email addresses are validated incorrectly. For instance "user.name@company.com" is invalid. Re pattern should be replaced with r"\"?([-a-zA-Z0-9.`?{}]+@\w+\.\w+)\"?"

**Comment by GoelJatin** [comment]
Hi @marekk1717 ,

I've updated the regex to **[^@]+@[^@]+\.[^@]+** to validate email addresses properly.

and tried out with different kinds of addresses.

Let us know if this works for your case as well.

This'll be added to the **[dev](https://github.com/CommvaultEngg/cvpysdk/tree/dev)** branch with the weekly check-in this Friday.

**Comment by GoelJatin** [comment]
Hi @marekk1717 ,

The code has been pushed to the **dev** branch.

Please let us know if you see any issues.

**Comment by marekk1717** [comment]
Hi @GoelJatin 
I've already tested it. Works OK. We can close this issue.
