### ISSUE TITLE
ExecuteQCommand support

### ISSUE THREAD

**Issue by marekk1717** [CommvaultEngg/cvpysdk#58]
Can we add support for ExecuteQCommand?
https://api.commvault.com/#b31cc2a9-7a09-bacd-6f30-a81556aff87e

**Comment by GoelJatin** [comment]
Hi @marekk1717 

We've added support for this, and it is currently in test phase internally.

This'll be added to the **[dev](https://github.com/CommvaultEngg/cvpysdk/tree/dev)** branch with the weekly check-in this Friday.

**Comment by GoelJatin** [comment]
Hi @marekk1717 ,

The code has been pushed to the **dev** branch.

[execute_qcommand](https://github.com/CommvaultEngg/cvpysdk/blob/dev/cvpysdk/commcell.py#L1673)

Please let us know if you see any issues.

**Comment by marekk1717** [comment]
Hi @GoelJatin 
I've already tested it. Works OK. We can close this issue.
