### ISSUE TITLE
cvpysdk.job.Job.summary does not return Virtual Server name

### ISSUE THREAD

**Issue by Gaeel** [CommvaultEngg/cvpysdk#59]
Hello,
When I'm calling .summary on <cvpysdk.job.Job>, I'm not able to get the Virtual Machine name, cvpysdk returns only the vCenter name as Client Name :

```python
commcell = Commcell('hostaname', 'user', 'passwd')
j = commcell.job_controller
job = j.get(12345)
print( job.summary )
```

By looking at the "Backup Job Summary", on the WebConsole, I'm able to see the VM name as the client name.
How can I get the backuped virtual machine name _via_ the API ?

**Comment by GoelJatin** [comment]
Hi @Gaeel ,

Can you check if **job.client_name** returns the value that you're looking for.

**Comment by Gaeel** [comment]
Hi @GoelJatin ,
job.client_name also returns the vCenter name if the backuped device is a VM.

**Comment by GoelJatin** [comment]
We'll check and get back to you soon.

**Comment by GoelJatin** [comment]
Hi @Gaeel ,

You can get the VM Name from the job details dict.

**`job.details['jobDetail']['clientStatusInfo']['vmStatus']`**

The above statement will return the list of all the VMs that are being backed up.


You can then access the VM Name from each element, like below

**`job.details['jobDetail']['clientStatusInfo']['vmStatus'][0]['vmName']`**


Hope this helps!

Let me know if you need any more info.

**Comment by Gaeel** [comment]
Hi,
job.details['jobDetails']['clientStatusInfo'] returns only the following output :
```json
{"failedClients": 0,
 "partialSuccessClients": 0,
 "pendingClient": 0,
 "skippedClients": 0,
 "successfullClients": 0,
 "totalClients": 0,
 "totalInProgressClients": 0}
```
My production CommServe is currently running v11 SP10. Maybe this feature has been added in following Service Packs.
Thank you for your support. Closing the issue. I will check back when it will be updated.
