### ISSUE TITLE
Cannot browse VSA  subclient

### ISSUE THREAD

**Issue by shyamdayals** [CommvaultEngg/cvpysdk#60]
First time trying to use SDK. I can browse File system agents fine, but doesn't work with Virtual Server.

Here is the code I am using.

commcell = Commcell('cvserver', 'cvuser', 'cvpass')

client    = commcell.clients.get('my_Vcenter')
agent     = client.agents.get('Virtual Server')
instance  = agent.instances.get('VMware')
backupset = instance.backupsets.get('defaultBackupSet')
subclient = backupset.subclients.get('subclient-CLUSTER')

print(subclient.content)

Here is the error message

    print(subclient.content)
  File "/usr/local/lib/python3.6/site-packages/cvpysdk/subclients/vssubclient.py", line 251, in content
    content_type = self.content_types[str(child['type'])]
KeyError: '6'

Thank you

Shyam

**Comment by Sowmyacv** [comment]
Hi Shyam,

This is because for we have not added support for all the content types . We have fixed this , you can make a pull request from our latest dev branch 

Thanks
Sowmya

**Comment by shyamdayals** [comment]
Thank you Sowmya. I can browse VSA clients through dev branch successfully. I have few follow up questions. 

Does the SDK supports following features for VSA clients ?

Is it possible to restore a VM to an alternate datastore ?
Browse a VM and restore individual files and directories ?
Restore a VM from Auxiliary/DASH copies at  DR site ?

Thanks

Shyam

**Comment by Sowmyacv** [comment]
> Thank you Sowmya. I can browse VSA clients through dev branch successfully. I have few follow up questions.
> 
> Does the SDK supports following features for VSA clients ?
> 
> Is it possible to restore a VM to an alternate datastore ?
> Browse a VM and restore individual files and directories ?
> Restore a VM from Auxiliary/DASH copies at DR site ?
> 
> Thanks
> 
> Shyam

Shyam,

1-> yes it is possible to restore to different datastore . specify this datastore in datastore parameter

full_vm_restore_out_of_place(vm_to_restore=None, restored_vm_name=None, vcenter_client=None, esx_host=None, datastore=None, overwrite=True, power_on=True, copy_precedence=0, disk_option='Original', transport_mode='Auto', proxy_client=None, source_ip=None, destination_ip=None)[source]

2-> yes it is possible to browse and specify the path in guest file restore 

Browse:
guest_files_browse(vm_path='\\', show_deleted_files=False, restore_index=True, from_date=0, to_date=0, copy_precedence=0, media_agent='')
     you can specify the vmguid in vmpath \\<vmguid> and get the files 

Restore:
guest_file_restore(vm_name=None, folder_to_restore=None, destination_client=None, destination_path=None, copy_precedence=0, preserve_level=1, unconditional_overwrite=False, restore_ACL=True, from_date=0, to_date=0, show_deleted_files=True, fbr_ma=None, browse_ma='')

Please specify the folder to restore from the response from browse

3-> look for this paramter copy_precedence in restores and then specify the copy_preceedence of auxillary copy

**Comment by klogan12** [comment]
Closing this issues , since support already exists.
