### ISSUE TITLE
restore fs_options support for advanced console options

### ISSUE THREAD

**Issue by questionsfrom** [CommvaultEngg/cvpysdk#61]
There does not seem to be an option to change the data restore rather than the stub. It is disabled by default.
Log message showing disabled:
FclRestore::OnMsgSetParams(4959) - Restore data instead of stub disabled

Is there a plan/way to make this feature accessible via the API?

**Comment by nikhiljain-cv** [comment]
Hi 
To enable "data instead of restore"  please add this ["restoreDataInsteadOfStub":True] in your fs_options restore parameter.

**Comment by questionsfrom** [comment]
Thank you! Didn't see this in the pip version but the latest clone worked. There is a bug where fs_options variable changes name to restore_options before the conditional is checked for advanced options. See line 1829 of instance.py.

```
if "fs_options" in value:
  _fs_option_value = value["fs_options"]
  if  _fs_option_value is not None:
      for _key in _advance_fs_keys:
          if _key in _fs_option_value:
              self._commonoption_restore_json[_key] = _fs_option_value[_key]
```

fs_options is not in value as it changes name in line 1431:

```
request_json = self._restore_json(
    paths=paths,
    overwrite=overwrite,
    restore_data_and_acl=restore_data_and_acl,
    copy_precedence=copy_precedence,
    from_time=from_time,
    to_time=to_time,
    restore_option=fs_options,
    schedule_pattern=schedule_pattern)
```

Setting fs_options=fs_options fixes the issue.
