### ISSUE TITLE
subclient.log_backup_storage_policy

### ISSUE THREAD

**Issue by AndreeaItu** [CommvaultEngg/cvpysdk#62]
Hi,

I am contacting you in regards of the updating the log_backup storage policy at the subclient level:
1.	I’ve tried first using the following:

>>> subclient._set_subclient_properties("_commonProperties['storageDevice']['deDuplicationOptions']['enableDeduplication']", 'FALSE')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\Administrator\PycharmProjects\cvpysdk\venv\lib\site-packages\cvpysdk\subclient.py", line 898, in _set_subclient_properties
    output = self._process_update_response(flag, response)
  File "C:\Users\Administrator\PycharmProjects\cvpysdk\venv\lib\site-packages\cvpysdk\subclient.py", line 990, in _process_update_response
    response.text))
cvpysdk.exception.SDKException: Response was not success
{
"errorMessage":"Service error","errorCode":102
} 

--- I’ve tried again to get “default” subclient log_policy for then updating the policy
>>> subclient = instance.subclients.get('default')
>>> subclient.log_backup_storage_policy
'SP_AVT_Test00'
>>> subclient._set_subclient_properties("_commonProperties['storageDevice']['logBackupStoragePolicy']['storagePolicyName']", 'SP_Crelan_Test')
>>> subclient.log_backup_storage_policy
'SP_Crelan_Test'

But the policy is not updated via GUI.

2.	The second way  I’ve tried is by using:
>>> subclient.log_backup_storage_policy = 'SP_Crelan_Test'
>>>  subclient.log_backup_storage_policy = 'SP_CSC_HAS'

In this case I get no error message but still the log_backup_policy is not being updated via GUI.

Could you please help me further,

Thank you for your time,

**Comment by GoelJatin** [comment]
Tracking it via mail thread internally
