### ISSUE TITLE
Is there a way to retrieve tape media inside the library?

### ISSUE THREAD

**Issue by newbeeeeeee** [CommvaultEngg/cvpysdk#64]
I am looking for a way to retrieve a list of tape media inside the tape library and i cant seem to find anything in the documentation. Has anyone does this before?

**Comment by spakhare** [comment]
@shailymehta, 

Can you please help here?

**Comment by shailymehta** [comment]
@newbeeeeeee 

Hi,
To display the media in a tape library:
[POST] <service request>/Qcommand/qlist media -l "<Tape library name>"

If you want list of media in a specific scratch pool :
[POST] <service request>/Qcommand/qlist media -l "<Tape library name>" -srp "<Scratchpool name>"

**Comment by shailymehta** [comment]
@newbeeeeeee

Hi,
To display the media in a tape library:
[POST] /Qcommand/qlist media -l Tape_library_name

If you want list of media in a specific scratch pool :
[POST] /Qcommand/qlist media -l Tape_library_name -srp Scratchpool_name

**Comment by newbeeeeeee** [comment]
@shailymehta 
I tried posting the qlist media command to QCommand API however all I got was this in response:

<CVGui_GenericResp errorMessage="Operation Successful!" errorCode="0" />

How can I retrieve a list of media or the output of the command?

**Comment by shailymehta** [comment]
@newbeeeeeee 
Which service pack level was this tried on?
I see there was a fix for this in v11 SP13 and I am able to get the list of media.

**Comment by klogan12** [comment]
Please open Commvault support ticket.
