### ISSUE TITLE
all_media_agents() - no attribute error

### ISSUE THREAD

**Issue by newbeeeeeee** [CommvaultEngg/cvpysdk#65]
I am trying to retrieve all media agents from commcell using the following:

ma = commcell.media_agents.all_media_agents()

Receiving the following error: 
AttributeError: 'MediaAgents' object has no attribute 'all_media_agents'

If I try has_media_agent(), it works fine.

**Comment by spakhare** [comment]
Hi @newbeeeeeee,

Can you please confirm the service pack version of cvpysdk you are using?

all_media_agents property was included to MediaAgents class in SP11.

Thanks,
Sachin
