### ISSUE TITLE
can't authenticate if ssl can't be validated

### ISSUE THREAD

**Issue by sorin2343** [CommvaultEngg/cvpysdk#66]
Hello
It seems that I can't authenticate on commserve if   certificate  can't be validated.
Error is : ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)
Thanks
Sorin Ispas

**Comment by GoelJatin** [comment]
Hi @sorin2343 ,

Could you please try connecting to the URL from a browser:
    `https://{{ WEBSERVER }}/webconsole/api/`

and see if the connection is successful.

We try to connect via HTTPS first, and expect that the certificate is valid, but if HTTPS is not available, only then we connect via HTTP.

If certificate validation fails, we do not allow the connection, for security purposes.

**Comment by sorin2343** [comment]
Hi ,

I already tested that and the connection was successful.
Additionally, the error message says that is a certificate error and assume that the connection has been made.

The code is very simple :
from cvpysdk.commcell import Commcell
commcell = Commcell(webconsole_hostname,commcell_username ,commcell_password )
commcell.logout()


Thanks
Sorin Ispas

**Comment by GoelJatin** [comment]
Could you please share the screenshot when tried from browser, and when tried from SDK with the full stack trace.

**Comment by sorin2343** [comment]
Hello ,

I attached 2 files .

Thanks
Sorin Ispas

**Comment by GoelJatin** [comment]
Hi @sorin2343 ,

I couldn't find any files attached.

Can you please share again.

**Comment by sorin2343** [comment]
Hi ,
It seems that I had a problem with http on webconsole after an version upgrade.
Now it works but I still want to connect to https.
It's not ok to  try to  connect over https and failed and then connect over http without clearly specifying .
Now I'm trying to connect with force https and the connection does not work.

What can I do ?

Thanks
Sorin Ispas
[execution_log.txt](https://github.com/CommvaultEngg/cvpysdk/files/2772017/execution_log.txt)

**Comment by GoelJatin** [comment]
Hi @sorin2343 ,

Does the WebConsole have a proper SSL certificate installed?

If so, the connection should work with HTTPS.

While opening the WebConsole from a browser, does it shows any kind of errors / warnings?

**Secure Connection:**
![image](https://user-images.githubusercontent.com/14715892/51379007-72378000-1b34-11e9-98d2-67d6a063bbb9.png)


**Unsecure connection:**
![image](https://user-images.githubusercontent.com/14715892/51379119-af9c0d80-1b34-11e9-8eb8-752223879657.png)

**Comment by sorin2343** [comment]
The certificate is a selfsign certificate .
[cid:image002.jpg@01D4AF24.F7C8C340]

**Comment by sorin2343** [comment]
hi 
any news ?
Thanks 
Sorin

**Comment by GoelJatin** [comment]
Hi @sorin2343 ,

We've added support for using self-signed certificates for authentication.

You can pass the certificates directory path during the Commcell object initialization.

`>>> commcell = Commcell(hostname, username, password, certificate_path={{ CERT_PATH }})`

Please update the code on your setup from the [**dev**](https://github.com/CommvaultEngg/cvpysdk/tree/dev/) branch

Please let me know if you see any issues.

Regards,
Jatin

**Comment by narabeltala** [comment]
Hi Same problem for me even thought curl to https://<webconsole>/webconsole/api  works still Comcell hoes not validate https. In browser though i see connection not secure warning for the commserver host.

Any option to bypass SSL cert validation ??

**Comment by GoelJatin** [comment]
Hi @narabeltala ,

You can pass the certificate directory path to the Commcell class initialization, as elaborated above.

**Comment by klogan12** [comment]
**Please open Commvault support ticket.**
