### ISSUE TITLE
Mark/Unmark Media Agent for Maintenance

### ISSUE THREAD

**Issue by AndreeaItu** [CommvaultEngg/cvpysdk#67]
Hi guys,

I am looking into creating a script for marking/unmarking the Media Agents for maintenance.
Did anybody tried this before?

Thank you in advance,

Andreea Itu

**Comment by GoelJatin** [comment]
Hi @AndreeaItu ,

I'm not sure about this, as this is related more to Media Agent than the SDK.

Please reach out to the Support team, and they should be able to help you in the best manner.
