### ISSUE TITLE
Just a question: How to use the SDK to send QCommand requests to API?

### ISSUE THREAD

**Issue by ryanxetm** [CommvaultEngg/cvpysdk#70]

**Comment by spakhare** [comment]
Hi @ryanxetm ,

Can you please share the details about the command you want to use? Maybe we can check if we can achieve the same via any of the existing API.

Between we do have an API **execute_qcommand** which can be triggered via Commcell object.
https://github.com/CommvaultEngg/cvpysdk/blob/master/cvpysdk/commcell.py#L1694

Example:
response_object = commcell_object.execute_qcommand('qlist client')
print(response_object.json())

**Comment by ryanxetm** [comment]
Hi @spakhare,

Thanks for your help. This is the function that I need.

Cheers,
Ryan
