### ISSUE TITLE
Bug in Email Verification

### ISSUE THREAD

**Issue by SayantanKhanra10** [CommvaultEngg/cvpysdk#71]
Current release (11.14)has a regex matching for the email which doesn't support any '.' in the email. The regex is:  **[\w]+@[\w]+\.[\w]+** 

example : abcd.efgh@gmail.com is not supported. Where as abcd@gmail.com works fine. 

Current master branch has the fix I see (**[^@]+@[^@]+\.[^@]+**). Can a new release of the master branch be done ASAP?

**Comment by GoelJatin** [comment]
Hi @SayantanKhanra10 ,

We'll try to get a release ASAP.

Will update the thread once that is done.

**Comment by klogan12** [comment]
@SayantanKhanra10  - Any reason to work on 11.14 branch on git.  Are you developing something on top of that branch?  If you are using SDK , you can download and install via commvault installer.

**Comment by klogan12** [comment]
Btw SP15 branch is created

**Comment by SayantanKhanra10** [comment]
@klogan12 To give some context, we bootstrap organisations in commvault island using our pipeline, which use cvpysdk.

we install cvpysdk using pipenv install in a virtual environment which gets its latest version from pypi repo.Thats why i wanted a new release of the master branch. 

Thanks for creating the new release though. I will test it out now.

**Comment by SayantanKhanra10** [comment]
The regex works fine. We can close this issue.
