### ISSUE TITLE
Additional fields on JobController.all_jobs()

### ISSUE THREAD

**Issue by ryanxetm** [CommvaultEngg/cvpysdk#72]
Is there a way we can add some additional fields we need on the` all_jobs()` function?

**Comment by spakhare** [comment]
@ryanxetm,

We already have a few fields to filter the jobs response. Can you please provide us with your requirement here?

You can find the available fields from below link.
https://github.com/CommvaultEngg/cvpysdk/blob/master/cvpysdk/job.py#L425

Thanks,
Sachin

**Comment by klogan12** [comment]
Open commvault support ticket for further changes.
