### ISSUE TITLE
Deactivate company 

### ISSUE THREAD

**Issue by SayantanKhanra10** [CommvaultEngg/cvpysdk#73]
I am trying to delete an organisation in commvault but I get the below error 

**File "/Users/skhanra/gitrepo/bootstrapperlib/.venv/lib/python3.7/site-packages/cvpysdk/organization.py", line 488, in delete
    raise SDKException('Organization', '104', 'Error: "{0}"'.format(error_message))
cvpysdk.exception.SDKException: Failed to delete the organization
Error: "Please deactivate company and then try again."** 

How can I deactivate the company? Didn't get much info from the documentation.

**Comment by Vairavaprakash** [comment]
Hi @SayantanKhanra10,

Support for activation and deactivation of an organization is provided in the Dev branch code,

and delete method is also updated to deactivate the organization before deleting it,

Install Dev branch code, that might help

**Comment by klogan12** [comment]
Updated SP15 branch with the fix.
