### ISSUE TITLE
getting ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by devsrm** [CommvaultEngg/cvpysdk#75]
[root@abc cvpysdk]# python
Python 3.7.3 (default, May  8 2019, 06:21:13)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cvpysdk.commcell import Commcell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/fisc/backup/python/lib/python3.7/site-packages/cvpysdk-11.17-py3.7.egg/cvpysdk/cvpysdk.py", line 66, in <module>
    from .exception import SDKException
ImportError: attempted relative import with no known parent package
>>>

**Comment by spakhare** [comment]
Hi @devsrm,

Can you please try to launch python shell from a different directory (different from python install path)? This might be because of the way python imports the libraries.

Thanks,
Sachin

**Comment by GoelJatin** [comment]
Hi @devsrm ,

Is this issue resolved?

Please let us know if you need any help.


**_Regards,
Jatin_**

**Comment by devsrm** [comment]
Hi Jatin/Sachin,

Yes, thank you. The issue is resolved.

Thanks,
Dev
