### ISSUE TITLE
cvpysdk 11.16.1

### ISSUE THREAD

**Issue by SayantanKhanra10** [CommvaultEngg/cvpysdk#77]
Hello.

I installed the cvpysdk version 11.16.1 today and found out it is actually broken. 

from cvpysdk.commcell import Commcell

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'cvpysdk'**

Can you guys please look into this asap?

**Comment by spakhare** [comment]
Hi @SayantanKhanra10,

Can you please confirm if you are using any virtual environments? I believe we need to manually install cvpysdk package in the virtual environment.

Thanks,
Sachin

**Comment by SayantanKhanra10** [comment]
I have used pipenv to install cvpysdk. 

I have hard pinned the 11.16.1 version in pipfile. 

This should install 11.16.1 version in the venv. Thats exactly the way i was installing 11.15 or 11.16 versions which seem to work as expected.

**Comment by spakhare** [comment]
Can you please retry using the latest version of cvpysdk? A newer version (11.16.2) was published today.

**Comment by spakhare** [comment]
Were you able to proceed with the latest version of cvpysdk? Can you please confirm?

**Comment by SayantanKhanra10** [comment]
Hey @spakhare I tried the 11.16.2 version today. Seems to working as expected. This issue can be closed.

Thanks!!

**Comment by spakhare** [comment]
Thanks
