### ISSUE TITLE
Virtual Server Agent

### ISSUE THREAD

**Issue by sephethus** [CommvaultEngg/cvpysdk#79]
Why does getting the Virtual Server agent not work for me? This returns empty. 

agent = client.agents.get('Virtual Server')

---------------------------------------------------------------------------
SDKException                              Traceback (most recent call last)
<ipython-input-18-1b941077d7a2> in <module>()
----> 1 agent = client.agents.get('Virtual Server')
      2 #backupset = agent.backupsets.get('CO Cluster07 f')
      3 #subclient = backupset.subclients.get('test_sub')
      4 #backupset.subclients.get("CO Cluster07 f")

/usr/local/lib/python3.6/site-packages/cvpysdk/client.py in agents(self)
   1938         """
   1939         if self._agents is None:
-> 1940             self._agents = Agents(self)
   1941 
   1942         return self._agents

/usr/local/lib/python3.6/site-packages/cvpysdk/agent.py in __init__(self, client_object)
    108 
    109         self._agents = None
--> 110         self.refresh()
    111 
    112         from .agents.exchange_database_agent import ExchangeDatabaseAgent

/usr/local/lib/python3.6/site-packages/cvpysdk/agent.py in refresh(self)
    271     def refresh(self):
    272         """Refresh the agents installed on the Client."""
--> 273         self._agents = self._get_agents()
    274 
    275 

/usr/local/lib/python3.6/site-packages/cvpysdk/agent.py in _get_agents(self)
    202                 return agent_dict
    203             else:
--> 204                 raise SDKException('Response', '102')
    205         else:
    206             raise SDKException('Response', '101', self._update_response_(response.text))

SDKException: Response received is empty

It returns nothing. It's most definitely a virtual server agent type it's literally right in the console:

![Capture](https://user-images.githubusercontent.com/545878/62136564-5b77a000-b2b2-11e9-8326-83a55ad89e7b.PNG)

**Comment by spakhare** [comment]
Hi @sephethus,

Can you please confirm the CvPySDK release version and your CommServer release version?

Thanks,
Sachin

**Comment by sephethus** [comment]
From the pip install: cvpysdk-11.16.2-py2.py3-none-any.whl
CommServer version: 11 sp15

**Comment by spakhare** [comment]
Can we please try with SP15 version of cvpysdk?

**Comment by sephethus** [comment]
I can try, is this sp16? How do I get 15?

**Comment by sephethus** [comment]
Nevermind I got version 15, same exact problem. It's an esxi host but that shouldn't make a single difference. It's a Virtual Server agent with multiple subclients in the defaultbackupset

**Comment by sephethus** [comment]
Ok I figured out what the issue is, there are two instances of that client, the main one has a different name using the FQDN, I typed the FQDN and it appears to have worked. Closing this sorry.
