### ISSUE TITLE
Will deleting a client release the license?

### ISSUE THREAD

**Issue by sephethus** [CommvaultEngg/cvpysdk#80]
CommVault recommends that the license be released for the client prior to deleting. Poor design on their part I suppose. Does this SDK have any means of doing that?

https://documentation.commvault.com/commvault/v11_sp9/article?p=features/deconfigure/deconfigure.htm

**Comment by Vairavaprakash** [comment]
Hi Sephethus,

Delete method in client.py module will delete the client and release the license associated with it.
https://github.com/CommvaultEngg/cvpysdk/blob/master/cvpysdk/client.py#L1199
