### ISSUE TITLE
Virtual Server: Cannot List all Subclients or List all VMs within...

### ISSUE THREAD

**Issue by sephethus** [CommvaultEngg/cvpysdk#81]
I'm trying to find some means of finding the backup status of a VM. I tried listing all subclients in the defaultBackupSet of a Virtual Server type agent, but that's not a thing I can do it seems. I want to find a specific VM buried in one of the several subclients in the default set. I can name a specific set and find it if it's in there, but I can't just list them all, loop through them and find them?

The backup status of a File System agent would also be ideal. Like, date/time of last full or incremental backup.

Is there a way to parse through the Backup history log of a given virtual server agent?

**Comment by Sowmyacv** [comment]
HI sephethus,

 we can use this API , 

/VM?propertyLevel=AllProperties&status=1 - It will return all the VMs backed up in that commcell
The response of this API will have field called backup job Id . The backup job id is the last job that backed up this VM.
you can use /Job API to check the status of that job if you want.
Hope i answered your question

**Comment by spakhare** [comment]
Hi @sephethus,

I believe this should help you. 
For any enhancement requests with SDK please open a support ticket.

Thanks,
Sachin
