### ISSUE TITLE
Can we detect/add new Tape Library and Tape Drives using CV Python SDK?

### ISSUE THREAD

**Issue by cssupratik** [CommvaultEngg/cvpysdk#83]
Hi CV Team,

I was exploring cvpysdk and just wanted to know if we have support for "Adding new Tape Library and Drives" using CV python SDK?

I can see a method to add new Storage Policy based Tape Library  but couldn't find any method to Detect/Add new Tape Library,
Please check the attached screenshot for the reference.

Example of Storage policy method : add_tape_sp(storage_policy_name, library, media_agent, drive_pool, scratch_pool)

**Comment by cssupratik** [comment]
![CV_Add_Tape](https://user-images.githubusercontent.com/41724016/62692986-3d671980-b9ef-11e9-9e53-dac91f4e69dc.jpg)

**Comment by Vairavaprakash** [comment]
Hi cssupratik,

Support for Tape library is not added yet, please create a support ticket.
we can add this in future SP's

**Comment by clariion** [comment]
Hi,

Is this future available now in 2021?

**Comment by saikat-cv** [comment]
Hi @clariion,

Detection and configuration of tape library is supported. 
https://github.com/Commvault/cvpysdk/blob/master/cvpysdk/storage.py#L2332

**Comment by clariion** [comment]
Is there any way to monitor default scratch pool, how many tapes are available, export, import of the tapes?

**Comment by spakhare** [comment]
Hi @clariion,

This is not yet supported.
