### ISSUE TITLE
converting jobid / subclientid to a client name

### ISSUE THREAD

**Issue by noam412** [CommvaultEngg/cvpysdk#85]
hey, does anyone has a clue of how to convert subclient id / job id to the client name ?

**Comment by spakhare** [comment]
Hi noam,

If you have job id, you can use job object to fetch the client name

job_object = commcell_obj.job_controller.get(job_id)
job_object.client_name

https://github.com/CommvaultEngg/cvpysdk/blob/master/cvpysdk/job.py#L56
https://github.com/CommvaultEngg/cvpysdk/blob/master/cvpysdk/job.py#L221

Thanks,
Sachin
