### ISSUE TITLE
storage_policies.py - no option to create storage policy at the top of global dedup policy

### ISSUE THREAD

**Issue by marekk1717** [CommvaultEngg/cvpysdk#87]
Can we add an option to create new storage policy at the top of existing global deduplication policy (storage pool) ?

**Comment by vinayakasingh** [comment]
Hi,
can you please open a support ticket for this enhancement. we will add the support.

**Comment by spakhare** [comment]
Thanks Vinay

Thanks,
Sachin

Sent from my iPhone

On Oct 15, 2019, at 7:27 AM, Vairavaprakash <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #87<https://github.com/CommvaultEngg/cvpysdk/issues/87>.

**Comment by marekk1717** [comment]
I'm Commvault employee ;) I can't create support tickets ;)

**Comment by spakhare** [comment]
Please create an MR to me. I will reassign to correct person.
