### ISSUE TITLE
Backup can't be started if storage policy name is empty

### ISSUE THREAD

**Issue by marekmkmk** [CommvaultEngg/cvpysdk#9]
Backup job can't be started if subclient contains empty storage policy name (storage policy is inherited from Client Group settings). 

> Traceback (most recent call last):
>   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.6/threading.py", line 864, in run
>     self._target(*self._args, **self._kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/cvpysdk-1.0.0-py3.6.egg/cvpysdk/backupset.py", line 538, in _run_backup
>     job = self.subclients.get(subclient_name).backup()
>   File "/usr/local/lib/python3.6/dist-packages/cvpysdk-1.0.0-py3.6.egg/cvpysdk/subclient.py", line 449, in get
>     self._backupset_object, subclient_name, self._subclients[subclient_name]['id']
>   File "/usr/local/lib/python3.6/dist-packages/cvpysdk-1.0.0-py3.6.egg/cvpysdk/subclient.py", line 554, in __init__
>     self._initialize_subclient_properties()
>   File "/usr/local/lib/python3.6/dist-packages/cvpysdk-1.0.0-py3.6.egg/cvpysdk/subclient.py", line 647, in _initialize_subclient_properties
>     storage_device['dataBackupStoragePolicy']['storagePolicyName']
> KeyError: 'storagePolicyName'

**Comment by GoelJatin** [comment]
Since we are running backup from Subclient object, storage policy needs to be defined.

The KeyError issue has been fixed.
