### ISSUE TITLE
cant get all failed jobs

### ISSUE THREAD

**Issue by noam412** [CommvaultEngg/cvpysdk#90]
hey, 
im trying to do a backup report of my own and my code does not get all the jobs that actually failed..
im connected to commcell using a username and the password, and i run over a file containing all the cilents names from the commcel.clients() function
heres the idea basically:

for client2 in file.readlines():
all_jobs=(commcell.job_controller.finished_jobs(client_name=client2.rstrip(),job_filter='Backup',show_aged_job=True,limit=72))

for job in all_jobs:
  if "Failed" in (all_jobs[job]['status']):
 job_object=commcell.job_controller.ger(job)
   print(job_object.start_time)
   print(job_object.stop_time)
   print(client2)

thats about it, if u see any syntax errors ignore that because the code is running,
i do get an output, but i cant get all the failed nodes for some reason, any help will be much appreiciated :)

**Comment by Vairavaprakash** [comment]
Hi Noam412,

The lookup_time by default is 24 hours for finished jobs, please increase the lookup time if needed, I think that should help

https://github.com/CommvaultEngg/cvpysdk/blob/master/cvpysdk/job.py#L722

Regards
Vairavaprakash

**Comment by noam412** [comment]
hey, i set it to 72 and it still doesnt show all the other jobs, still only one job..

**Comment by Vairavaprakash** [comment]
can you please try from GUI with the same job filters and check whether the results match or not?

**Comment by noam412** [comment]
yeah i did, thats why i said it didnt work because in the commcell GUI there is 18 failed nodes, thats why its strange

**Comment by Vairavaprakash** [comment]
This functionality works as expected when we tried in house,

can you please open a support ticket, we will check this further

**Comment by noam412** [comment]
can you please show me exactly what you wrote ?

**Comment by Vairavaprakash** [comment]
commcell_obj.job_controller.finished_jobs(client_name='client_name', lookup_time=72, job_filter='Backup', show_aged_job=True, limit=30)

can you please let us know in which SP you are trying this?

**Comment by Vairavaprakash** [comment]
Closing this issue, please reopen if any help is needed
