### ISSUE TITLE
Additional information for BackupJobSummary in dev branch

### ISSUE THREAD

**Issue by ronnie147** [CommvaultEngg/cvpysdk#91]
Hi,
I would like to get additional information on API what uses in BackupJobSummary class in cvpysdk/cvpysdk/reports/report.py
I need to filter by Client Computer Groups and times (last 24 hours). Is it possible?

**Comment by Vairavaprakash** [comment]
Hi Ronnie147,

Yes, it is possible using the below API call

https://github.com/CommvaultEngg/cvpysdk/blob/master/cvpysdk/reports/report.py#L135

we have to add a method for setting the filters for the report, and then post using the API call

The method should modify the API call payload

**Comment by ronnie147** [comment]
Hi Vairavaprakash,

then I need to change request body:
[https://github.com/CommvaultEngg/cvpysdk/blob/7e68dcb308882c86dd0d5b02b04fdc4c705f0d59/cvpysdk/reports/report.py#L149](url)

Which attributes are responsible for "computer selection list" and "lookup time" filters fro the report?

**Comment by avinashjsap** [comment]
Hi Ronnie147,
                      Apologies for the delay. 

- For filtering Computer selection list, please **replace** the following key-value pair

From
`"computerSelectionList": {"includeAll": True}`
 
To
```
"computerSelectionList": {
    "includeAll": False,
    "clientGroupList": [
        {
            "clientGroupName": "client_group_1"
        }
    ],
    "clientList": [
        {
            "clientName": "client1"
        },
        {
            "clientName": "client2"
        },
        {
            "clientName": "client3"
        }
    ]

}
```
(set the required client and client groups appropriately).

- For lookup time filter, **add** the following key-value pair under "reportOption". 
("timeRangeOption" will be a sibling of "computerSelectionList")

```
"timeRangeOption": {
    "TimeZoneName": "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi",
    "toTimeValue": "30",
    "type": 13
}
```
(set the timezone and value appropriately)

**Comment by ronnie147** [comment]
Hi avinashjsap,

It works fine. Can I use timezone from CommServe?

I'm interested in some more settings. Are there any documentation for this API?
I would like to set "Backup Types" (add Incremental and Differential) and "Job Status" (exclude "No schedule).

**Comment by chetan-deshpande** [comment]
Hi Ronnie147,

Support to these options is not yet available, can you please raise support ticket for this with all required options, we will add this in next service pack.
