### ISSUE TITLE
Question with SQL Integraiton

### ISSUE THREAD

**Issue by KezHalls** [CommvaultEngg/cvpysdk#92]
Hi
I am trying to utilise your toolkit to perform SQL backups and restores.  Currently I am trying to: 

1. loop through the list of objects to check if the server is part of the "Availability Replica Clients" list (ie: a HA client)

2. if so then save the backup to a flat file location

My issues so far have been

- I have tried to return all properties at server and SQL server instance level but am unable to retrieve the information on "Availability Replica Clients".

- I have not been able to figure out how to save it to a folder location

**Comment by Vairavaprakash** [comment]
Hi KezHalls,

Your first query is not supported yet, please open a support ticket if this support is required

As a workaround, you can set property level as 20 to receive information about availability replica's as part of instance properties

https://github.com/CommvaultEngg/cvpysdk/blob/master/cvpysdk/services.py#L67

Can you please explain more about your second query?

**Comment by spakhare** [comment]
Please open a support ticket for adding this enhancement.
