### ISSUE TITLE
what is the API payload to install Oracle agent in a server using commvault rest api

### ISSUE THREAD

**Issue by devsrm** [CommvaultEngg/cvpysdk#93]
what is the API payload to install Oracle agent in a server using commvault rest api

**Comment by Vairavaprakash** [comment]
Hi Devsrm,

Below method can be used to install software on client machines

https://github.com/CommvaultEngg/cvpysdk/blob/master/cvpysdk/deployment/install.py#L199

API payload is available as part of the method

**Comment by devsrm** [comment]
I checked the above link, there is no Oracle agent information passed in the payload. I'm actually looking to use the commvault REST API instead of the cvpysdk. Basically, i'm using the below URL and gave the required headers ,but not sure on what to be passed in the body.

http://<commserver>::81/SearchSvc/CVWebService.svc/InstallClient

**Comment by devsrm** [comment]
i'm specifically looking on what needs to be passed in the API payload while using the below URL to install Oracle agent in a server.
http://:81/SearchSvc/CVWebService.svc/InstallClient. I tried using the below but got the response as Request body is empty or format is invalid.

below is what i passed in the body

{
"rebootClient": false,
"createPseudoClientRequest": {
"registerClient": true,
"clientInfo": {
"clientType": 0

    }
},
"packages": [
    {
        "packageId": 1204,
        "packageName": "Oracle"
    }
],
"clientAuthForJob": {
    "userName": "*****",
    "password": "*****"
},
"entities": [
    {
        "clientId": 3,
        "clientName": "test123",
        "hostName": "test.dmn.com"
    }
    
]
}

**Comment by spakhare** [comment]
Please open a support ticket. We will help you find a solution to this.
