### ISSUE TITLE
mssql - restore_to_destination_server - restore_path

### ISSUE THREAD

**Issue by marekk1717** [CommvaultEngg/cvpysdk#94]
please could you give me an example of restore_path parameter in restore_to_destination_server function of mssql instance? Let's say I would like to to restore with new name, database and log should be restore to new path

**Comment by garcichr** [comment]
Database renames and restoring to a new path will both utilize the ‘restore_path’ list. 
•	The format is: ['|<<original_database_name>>|#12!<<new_database_name>>|#12!<<logical_file_name>>|#12!<<new_path_with_file>>|#12!<<original_path_with_file>>’]

•	This is an example of database rename only
[
'|myporp1|#12!myporp1_renamed|#12!myporp1|#12!C:\\OriginalFolder\\myporp1_blzg.mdf|#12!C:\\OriginalFolder\\myporp1.mdf',
'|myporp1|#12!myporp1_renamed|#12!myporp1_log|#12!C:\\OriginalFolder\\myporp1_log.ldf|#12!C:\\OriginalFolder\\myporp1_log.ldf',
'|myporp1|#12!myporp1_renamed|#12!myporp111|#12!C:\\OriginalFolder\\1myporp11.ndf|#12!C:\\OriginalFolder\\1myporp11.ndf',
'|myporp1|#12!myporp1_renamed|#12!myporp112|#12!C:\\OriginalFolder\\1myporp12.ndf|#12!C:\\OriginalFolder\\1myporp12.ndf',
'|myporp1|#12!myporp1_renamed|#12!myporp113|#12!C:\\OriginalFolder\\1myporp13.ndf|#12!C:\\OriginalFolder\\1myporp13.ndf',
'|myporp1|#12!myporp1_renamed|#12!myporp121|#12!C:\\OriginalFolder\\1myporp21.ndf|#12!C:\\OriginalFolder\\1myporp21.ndf',
'|myporp1|#12!myporp1_renamed|#12!myporp122|#12!C:\\OriginalFolder\\1myporp22.ndf|#12!C:\\OriginalFolder\\1myporp22.ndf',
'|myporp1|#12!myporp1_renamed|#12!myporp123|#12!C:\\OriginalFolder\\1myporp23.ndf|#12!C:\\OriginalFolder\\1myporp23.ndf',
'|myporp1|#12!myporp1_renamed|#12!myporp131|#12!C:\\OriginalFolder\\1myporp31.ndf|#12!C:\\OriginalFolder\\1myporp31.ndf',
'|myporp1|#12!myporp1_renamed|#12!myporp132|#12!C:\\OriginalFolder\\1myporp32.ndf|#12!C:\\OriginalFolder\\1myporp32.ndf',
'|myporp1|#12!myporp1_renamed|#12!myporp133|#12!C:\\OriginalFolder\\1myporp33.ndf|#12!C:\\OriginalFolder\\1myporp33.ndf'
]

•	This is an example of database rename and new file location
[
'|myporp1|#12!myporp1_renamed|#12!myporp1|#12!G:\\NewRestoreFolder\\myporp1_dxbo.mdf|#12!C:\\OriginalFolder\\myporp1.mdf',
'|myporp1|#12!myporp1_renamed|#12!myporp1_log|#12!G:\\NewRestoreFolder\\myporp1_log_dxbo.ldf|#12!C:\\OriginalFolder\\myporp1_log.ldf',
'|myporp1|#12!myporp1_renamed|#12!myporp111|#12!G:\\NewRestoreFolder\\1myporp11_dxbo.ndf|#12!C:\\OriginalFolder\\1myporp11.ndf',
'|myporp1|#12!myporp1_renamed|#12!myporp112|#12!G:\\NewRestoreFolder\\1myporp12_dxbo.ndf|#12!C:\\OriginalFolder\\1myporp12.ndf',
'|myporp1|#12!myporp1_renamed|#12!myporp113|#12!G:\\NewRestoreFolder\\1myporp13_dxbo.ndf|#12!C:\\OriginalFolder\\1myporp13.ndf',
'|myporp1|#12!myporp1_renamed|#12!myporp121|#12!G:\\NewRestoreFolder\\1myporp21_dxbo.ndf|#12!C:\\OriginalFolder\\1myporp21.ndf',
'|myporp1|#12!myporp1_renamed|#12!myporp122|#12!G:\\NewRestoreFolder\\1myporp22_dxbo.ndf|#12!C:\\OriginalFolder\\1myporp22.ndf',
'|myporp1|#12!myporp1_renamed|#12!myporp123|#12!G:\\NewRestoreFolder\\1myporp23_dxbo.ndf|#12!C:\\OriginalFolder\\1myporp23.ndf',
'|myporp1|#12!myporp1_renamed|#12!myporp131|#12!G:\\NewRestoreFolder\\1myporp31_dxbo.ndf|#12!C:\\OriginalFolder\\1myporp31.ndf',
'|myporp1|#12!myporp1_renamed|#12!myporp132|#12!G:\\NewRestoreFolder\\1myporp32_dxbo.ndf|#12!C:\\OriginalFolder\\1myporp32.ndf',
'|myporp1|#12!myporp1_renamed|#12!myporp133|#12!G:\\NewRestoreFolder\\1myporp33_dxbo.ndf|#12!C:\\OriginalFolder\\1myporp33.ndf'
]

Also, **_restore_to_destination_server_** is being deprecated. You can use just **_restore_** function to restore to another instance by passing the ‘destination_instance’ input.

**Comment by marekk1717** [comment]
Does it look ok ?
```
['|AdventureWorks2014|#12!AdventureWorks2014_REST1|#12!AdventureWorks2014_Data|#12!D:\restoretest2\AdventureWorks2014_Data.mdf|#12!C:\Program Files\Microsoft SQL Server\MSSQL12.COMMVAULT\MSSQL\DATA\AdventureWorks2014_Data.mdf',
'|AdventureWorks2014|#12!AdventureWorks2014_REST1|#12!AdventureWorks2014_Log|#12!D:\restoretest2\AdventureWorks2014_Log.ldf|#12!C:\Program Files\Microsoft SQL Server\MSSQL12.COMMVAULT\MSSQL\DATA\AdventureWorks2014_Log.ldf']
```

```
---------------------------------------------------------------------------
SDKException                              Traceback (most recent call last)
<ipython-input-139-2732eb213bd3> in <module>
----> 1 sqljr1 = sqli1.restore_to_destination_server(content_to_restore=['AdventureWorks2014'], destination_server='cs\\commvault', restore_path=restore_path1)

c:\users\mkedzierski\appdata\local\programs\python\python37-32\lib\site-packages\cvpysdk-11.20-py3.7.egg\cvpysdk\instances\sqlinstance.py in restore_to_destination_server(self, content_to_restore, destination_server, drop_connections_to_databse, overwrite, restore_path)
    645         )
    646 
--> 647         return self._process_restore_response(request_json)
    648 
    649     @property

c:\users\mkedzierski\appdata\local\programs\python\python37-32\lib\site-packages\cvpysdk-11.20-py3.7.egg\cvpysdk\instances\sqlinstance.py in _process_restore_response(self, request_json)
    289         else:
    290             response_string = self._commcell_object._update_response_(response.text)
--> 291             raise SDKException('Response', '101', response_string)
    292 
    293     def _get_sql_restore_options(self, content_to_restore):

**SDKException: Response was not success
Request body is empty or format is invalid.**
```

**Comment by garcichr** [comment]
Try this:
sqljr1 = sqli1.**restore**(content_to_restore=['AdventureWorks2014'], **destination_instance**='cs\\\commvault', restore_path=restore_path1)

**Comment by marekk1717** [comment]
still doesn't work

In Chrome developer tools, request looks like this. From what I see, Command Center passes also parameter called deviceInfo. 

agentSpecificOptions: {"overWrite":true,"dropConnectionsToDatabase":true,"pointOfTimeRst":false,"latestBkpData":true,"sqlRecoverType":0,"device":["AdventureWorks2014\u0012NEWDB\u0012AdventureWorks2014_Data\u0012D:\\RESTORETEST2\\AdventureWorks2014_Data.mdf\u0012C:\\Program Files\\Microsoft SQL Server\\MSSQL12.COMMVAULT\\MSSQL\\DATA\\AdventureWorks2014_Data.mdf","AdventureWorks2014\u0012NEWDB\u0012AdventureWorks2014_Log\u0012D:\\RESTORETEST2\\AdventureWorks2014_Log.ldf\u0012C:\\Program Files\\Microsoft SQL Server\\MSSQL12.COMMVAULT\\MSSQL\\DATA\\AdventureWorks2014_Log.ldf"]**,**"deviceInfo":["15\tNEWDB\t0\t \tD:\\RESTORETEST2\\AdventureWorks2014_Data.mdf\tAdventureWorks2014_Data\t215220224\tAdventureWorks2014\t","15\tNEWDB\t0\t \tD:\\RESTORETEST2\\AdventureWorks2014_Log.ldf\tAdventureWorks2014_Log\t18874368\tAdventureWorks2014\t"]}****

**Comment by garcichr** [comment]
My example didn't reflect the path with double slashes but please verify yours does. No need for deviceInfo here so no worries.

['|AdventureWorks2014|#12!AdventureWorks2014_REST1|#12!AdventureWorks2014_Data|#12!D:\\\restoretest2\\\AdventureWorks2014_Data.mdf|#12!C:\\\Program Files\\\Microsoft SQL Server\\\MSSQL12.COMMVAULT\\\MSSQL\\\DATA\\\AdventureWorks2014_Data.mdf',
'|AdventureWorks2014|#12!AdventureWorks2014_REST1|#12!AdventureWorks2014_Log|#12!D:\\\restoretest2\\\AdventureWorks2014_Log.ldf|#12!C:\\\Program Files\\\Microsoft SQL Server\\\MSSQL12.COMMVAULT\\\MSSQL\\\DATA\\\AdventureWorks2014_Log.ldf']

**Comment by marekk1717** [comment]
Still doesn't work.
"Request body is empty or format is invalid."

**Comment by spakhare** [comment]
Please open a support ticket. We will help you find a solution to this.
