### ISSUE TITLE
add a group to security associations on clients

### ISSUE THREAD

**Issue by tonyhogsten** [CommvaultEngg/cvpysdk#96]
Hi,

We have a use-case where we need to add group associations to a client. Currently it's only supported to add a user with the method add_user_associations(). The method is hardcoded to set user=True meaning that we are unable to set groups instead. 

I want to be able to do something like this: 

```python
associations_list: [
        {
          "group_name": "customer\\Tenant Admin",
          "role_name": "Tenant Admin"
        }
```

client.add_group_association(associations_list).

**Comment by spakhare** [comment]
Hi @tonyhogsten,

Can you please open Commvault support ticket? We will help you with the enhancements.

Thanks
