### ISSUE TITLE
PyPI version 11.19 missing needed fix

### ISSUE THREAD

**Issue by radssh** [CommvaultEngg/cvpysdk#97]
Installing latest version (11.19) from PyPI via pip, the unix_features handling is broken in deployment/install.py:

        if windows_features:
            os_type = 0
            install_options = [{'osType': 'Windows', 'ComponentId': feature_id}
                               for feature_id in windows_features]

        elif unix_features:
            os_type = 1
            install_options = [{'osType': 'Unix', 'ComponentId': feature_id}
                               for feature_id in **windows_features**]

This appears to have been addressed in 24ea1dce6811c1a98097e97934ccc4b0b46fdc31 dated 1/31/2020 but not in the PyPI version  Released: Mar 16, 2020

**Comment by Vairavaprakash** [comment]
Hi Radssh,

This is fixed in 11.20.
11.20 will be uploaded to Pypi on June 15 2020
